# Generated by Django 6.0.6 on 2026-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía o Información'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='ira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IRA'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='temas_interes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Temas de Interés'),
        ),
    ]
