# Generated by Django 6.0.6 on 2026-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0002_perfilestudiante_bio_perfilestudiante_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='puntos_prestigio',
            field=models.IntegerField(default=0, verbose_name='Puntos de Prestigio'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='rango',
            field=models.CharField(default='MAESTRO', max_length=50, verbose_name='Rango'),
        ),
    ]
