# Generated by Django 6.0.6 on 2026-07-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0003_perfilestudiante_puntos_prestigio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilestudiante',
            name='rango',
        ),
    ]
