# Generated by Django 6.0.6 on 2026-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulo_usuarios", "0004_recompute_rangos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilestudiante",
            name="rango",
            field=models.CharField(
                default="prepo", max_length=50, verbose_name="Rango"
            ),
        ),
    ]
