# Generated by Django 6.0.6 on 2026-07-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0004_remove_perfilestudiante_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='rango',
            field=models.CharField(default='MAESTRO', max_length=50, verbose_name='Rango'),
        ),
    ]
