# Generated by Django 6.0.6 on 2026-07-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0004_recompute_rangos'),
        ('modulo_usuarios', '0005_perfilestudiante_rango'),
    ]

    operations = [
    ]
