# Generated by Django 6.0.6 on 2026-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0006_merge_20260710_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='rango',
            field=models.CharField(default='prepo', max_length=50, verbose_name='Rango'),
        ),
    ]
