# Generated by Django 6.0.6 on 2026-07-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0005_alter_perfilestudiante_rango'),
        ('modulo_usuarios', '0007_alter_perfilestudiante_rango'),
    ]

    operations = [
    ]
