# Generated by Django 6.0.6 on 2026-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0008_merge_20260714_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='foto_perfil',
            field=models.ImageField(default='perfiles/avatares/default.png', upload_to='perfiles/avatares/'),
        ),
    ]
