# Generated by Django 6.0.6 on 2026-07-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0009_alter_perfilestudiante_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='suscripciones',
            field=models.ManyToManyField(blank=True, related_name='suscriptores', to='modulo_usuarios.perfilestudiante'),
        ),
    ]
