"""
Django settings for nucleo_notable project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-21@zr3e!x@k@q6@2nujytx#*o0bs4#ed-z%lea=&(qcqqe+rbw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modulo_apuntes',
    'modulo_prestigio',
    'behave_django',  # <-- pa usar el behave pero del Django si no, no funca
    'modulo_usuarios',
    'modulo_notificaciones.apps.ModuloNotificacionesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nucleo_notable.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- Aquí le decimos a Django que busque plantillas también en la carpeta 'templates' que creamos en la raíz del proyecto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Notificaciones
                'modulo_notificaciones.context_processors.notificaciones_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'nucleo_notable.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Permite mostrar páginas y PDFs en iframes dentro del mismo origen.
X_FRAME_OPTIONS = 'SAMEORIGIN'
# Le decimos a Django dónde guardar el CSS global
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# La ruta pública que verán los usuarios en el navegador (ej. tudominio.com/media/archivo.pdf)
MEDIA_URL = '/media/'
# La ruta física absoluta en el disco duro de tu computadora (o futuro servidor)
# donde Django va a crear la carpeta y guardar los archivos reales.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# A dónde redirigir al usuario si el login es exitoso (puedes cambiarlo a la ruta de tus apuntes luego)
LOGIN_REDIRECT_URL = 'publicaciones:lista_apuntes'

# A dónde enviar al usuario si intenta acceder a una vista protegida sin iniciar sesión
LOGIN_URL = 'usuarios/login/'

