# Generated by Django 6.0.6 on 2026-07-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulo_publicaciones_apuntes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apunte",
            name="acceso_restringido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apunte",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ApunteGuardado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_guardado", models.DateTimeField(auto_now_add=True)),
                (
                    "apunte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardados",
                        to="modulo_publicaciones_apuntes.apunte",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardados",
                        to="modulo_usuarios.perfilestudiante",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "apunte"),
                        name="unique_guardado_por_usuario_apunte",
                    )
                ],
            },
        ),
    ]

