# Generated by Django 6.0.6 on 2026-07-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_usuarios', '0010_perfilestudiante_suscripciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoSuscripcionOtorgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hito', models.PositiveIntegerField()),
                ('puntos_otorgados', models.PositiveIntegerField()),
                ('otorgado_en', models.DateTimeField(auto_now_add=True)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_suscripcion_otorgados', to='modulo_usuarios.perfilestudiante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publicador', 'hito'), name='unique_hito_suscripcion_por_publicador')],
            },
        ),
    ]
