# Generated by Django 6.0.6 on 2026-06-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("modulo_usuarios", "0003_perfilestudiante_puntos_prestigio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apunte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Apunte"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción o Resumen")),
                (
                    "contenido",
                    models.FileField(
                        upload_to="apuntes/documentos/%Y/%m/",
                        verbose_name="Archivo del Apunte",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "portada",
                    models.ImageField(
                        blank=True, null=True, upload_to="apuntes/portadas/%Y/%m/"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuntes",
                        to="modulo_usuarios.perfilestudiante",
                    ),
                ),
            ],
        ),
    ]
