# Generated by Django 6.0.6 on 2026-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulo_apuntes", "0002_apunte_estado_y_guardados"),
    ]

    operations = [
        migrations.AddField(
            model_name="apunte",
            name="total_descargas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
