# Generated by Django 6.0.6 on 2026-07-16 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apuntes', '0003_apunte_total_descargas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apunte',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador / Privado'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado (Listo para publicar)'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Avalado'), ('RECHAZADO', 'Requiere Cambios')], default='PENDIENTE', max_length=20)),
                ('comentario_autor', models.TextField(blank=True, help_text='¿Qué quieres que revise específicamente?', null=True)),
                ('comentario_revisor', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(auto_now=True)),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='modulo_apuntes.apunte')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
