# Generated by Django 6.0.6 on 2026-07-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_apuntes', '0004_apunte_estado_solicitudrevision'),
        ('modulo_apuntes', '0005_comentario'),
    ]

    operations = [
    ]
