# Generated by Django 6.0.6 on 2026-07-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulo_apuntes", "0006_merge_20260716_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="contenido",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
